apps/courses/urls.py
# Author Caozy
from django.conf.urls import url, include
from courses.views import CourseListView,CourseDetailView,CourseInfoView,CourseCommentView,AddCommentsView,CoursePlayView

urlpatterns = [
    # 机构模板继承
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    url(r'^add_comment/$', AddCommentsView.as_view(), name='add_comment'),

    url(r'^video/(?P<video_id>\d+)/$', CoursePlayView.as_view(), name='video_play'),

]
app_name = 'course'

apps/organization/urls.py
# Author Caozy
from django.conf.urls import url, include
from organization.views import OrgView, UserAskView, OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView,TeacherListView,TeacherDetailView

urlpatterns = [
    # 机构模板继承
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    url(r'^user_ask/$', UserAskView.as_view(), name='user_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    # 授课教师
    url(r'^teacher/list/$', TeacherListView.as_view(), name='org_teacher_list'),
    # 讲师详情页
    url(r'^teachers_detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='org_teacher_detail'),
]
app_name = 'organization'

apps/users/urls.py
# Author Caozy
from django.conf.urls import url, include
from users.views import UserInfoView,UploadImageView,UpdatePwdView,SendEmailCodeView,UpdateEmailView,MyCourseView,FavOrgView,FavTeacherView,FavCourseView,MessageView

urlpatterns = [
    # 机构模板继承
    url(r'^info/$', UserInfoView.as_view(), name='info'),
    # 修改头像
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),
    # 修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    # 获取修改邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='send_email_code'),
    # 修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),
    # 我的收藏
    url(r'^fav_org/$', FavOrgView.as_view(), name='fav_org'),
    url(r'^fav_teacher/$', FavTeacherView.as_view(), name='fav_teacher'),
    url(r'^fav_course/$', FavCourseView.as_view(), name='fav_course'),
    # 我的消息
    url(r'^message/$', MessageView.as_view(), name='message'),

]
app_name = 'users'

mxonline/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
import xadmin  # admin # admin123
from django.views.generic import TemplateView
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView
from organization.views import OrgView
from django.views.static import serve
from mxonline.settings import MEDIA_ROOT,STATIC_ROOT
from users.views import IndexView
from mxonline import settings

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', TemplateView.as_view(template_name='login.html'),name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url(r'^modify/$', ModifyPwdView.as_view(), name='modify_pwd'),

    # org模板继承
    url(r'^org/', include('organization.urls', namespace='org')),
    # course模板继承
    url(r'^course/', include('courses.urls', namespace='course')),
    # 配置文件上传的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # users模板继承
    url(r'^users/', include('users.urls', namespace='users')),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}),

]

# 全局配置404/500页面
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/models.py
# -*- coding:utf-8 -*-

from django.db import models
from datetime import datetime
from organization.models import CourseOrg,Teacher


# Create your models here.
class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, null=True, blank=True, verbose_name=u'课程机构')
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    category = models.CharField(max_length=200, default=u'后端开发', verbose_name=u'课程类别')
    is_banner=models.BooleanField(default=False,verbose_name=u'是否轮播')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情')
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=20, verbose_name=u'课程级别')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default='1', verbose_name=u'教师')
    course_note = models.CharField(max_length=300, default='',verbose_name=u'课程须知')
    teacher_note = models.TextField(default='',verbose_name=u'教师提示')
    learn_time = models.IntegerField(default=0, verbose_name=u'学习时长（分钟）')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'封面图片')
    click_nums = models.IntegerField(default=0, verbose_name=u'点击量')
    tag = models.CharField(max_length=10, verbose_name=u'课程推荐', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_user(self):
        return self.usercourse_set.all()[:5]

    def get_learn_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程信息')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_lesson_video(self):
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    learn_time = models.IntegerField(default=0, verbose_name=u'学习时长（分钟）')
    url = models.CharField(max_length=50, default='', verbose_name=u'资源链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'资源名称')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>

    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}课程机构列表 - 慕学在线网{% endblock %}</title>
    {% block css %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% block js %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            {% if request.user.is_authenticated %}
                <div class="top">
                    <div class="wp">
                        <div class="fl">
                            <p>服务电话：<b>x0000000000</b></p>
                        </div>
                        <!--登录后跳转-->

                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width='20' height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>{{ request.user.nick_name }}</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="{% url 'users:message' %}">
                        <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                    </a>
                </div>
            {% else %}
                <div class="top">
                    <div class="wp">
                        <div class="fl">
                            <p>服务电话：<b>33333333</b></p></div>
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    </div>
                </div>
            {% endif %}


            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% if request.path == '/' %}class="active"{% endif %}>
                                <a href="{% url 'index' %}">首页</a></li>
                            <li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
                                <a href="{% url 'course:course_list' %}">公开课
                                    <img class="hot" src="{% static 'images/nav_hot.png' %}"></a></li>
                            <li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
                                <a href="{% url 'org:org_teacher_list' %}">授课讲师</a></li>
                            <li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}>
                                <a href="{% url 'org:org_list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
</section>
<!--crumbs start-->
{% block bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block body %}

{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
{% block custom_js %}
    <script>
        $(function () {
            $('#jsStayBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/org/add_ask/",
                    data: $('#jsStayForm').serialize(),
                    async: true,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('#jsStayForm')[0].reset();
                            alert("提交成功")
                        } else if (data.status == 'fail') {
                            $('#jsCompanyTips').html(data.msg)
                        }
                    },
                });
            });
        })

    </script>
{% endblock %}

</body>
</html>

templates/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    公开课
{% endblock %}
{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block body %}

    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_time }}</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"
                                       href="{% url 'course:course_info' course.id %}"><span>章节</span></a>
                                </li>
                                <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a>
                                </li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in lesson_comments %}
                                <li class="post-row">
                                    <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}'
                                                               width='40' height='40'/></span>
                                    </div>
                                    <div class="bd">
                                        <div class="tit">
                                            <span target="_blank">{{ comment.user.username }}</span>
                                        </div>
                                        <p class="cnt">{{ comment.comments }}</p>
                                        <div class="footer clearfix">
                                            <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}


                            </ul>
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for course_sourcse in course_sourses %}
                                    <li>
                                        <span><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_sourcse.name }}</span>
                                        <a href="{{ MEDIA_URL }}{{ course_sourcse.download }}" class="downcode"
                                           target="_blank" download="" data-id="274" title="">下载</a>
                                    </li>
                                    {% endfor %}

                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="/u/315464/courses?sort=publish" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_prosition }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.course_note }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_note }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">

                                            <li class="curr">
                                                <a href="course-detail.html" target="_blank">
                                                    <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg"
                                                         alt="django与vuejs实战项目2">
                                                    <span class="name autowrap">django与vuejs实战项目2</span>
                                                </a>
                                            </li>

                                            <li class="curr">
                                                <a href="course-detail.html" target="_blank">
                                                    <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                                    <span class="name autowrap">python面向对象</span>
                                                </a>
                                            </li>

                                            <li class="curr">
                                                <a href="course-detail.html" target="_blank">
                                                    <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                                    <span class="name autowrap">python文件处理</span>
                                                </a>
                                            </li>

                                            <li class="curr">
                                                <a href="course-detail.html" target="_blank">
                                                    <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                                    <span class="name autowrap">django入门</span>
                                                </a>
                                            </li>

                                            <li class="curr">
                                                <a href="course-detail.html" target="_blank">
                                                    <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                                    <span class="name autowrap">xadmin进阶开发</span>
                                                </a>
                                            </li>

                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                         alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>

{% endblock %}
{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function () {
        var comments = $("#js-pl-textarea").val()
        if (comments == "") {
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url: "{% url 'course:add_comment' %}",
            data: {'course_id': {{ course.id }}, 'comments': comments},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "{% url 'login' %}";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == 'success') {
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}个人信息- 慕学在线网{% endblock %}
{% block css %}{% endblock %}
{% block js %}{% endblock %}
{% block bread %}我的收藏{% endblock %}

{% block right_content %}

    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:fav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                </ul>
            </div>


            <div class="companycenter">
                <div class="group_list brief">
                {% for course in course_list %}
                    <div class="module1_5 box">
                        <a href="{% url 'course:course_detail' course.id %}">
                            <img width="214" height="190"
                                 src="{{ MEDIA_URL }}{{ course.image }}"/>
                        </a>
                        <div class="des">
                            <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                            <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                            <span class="fr">学习人数：{{ course.students }}</span>
                        </div>
                        <div class="bottom">
                            <span class="fl">{{ course.course_org.name }}</span>
                            <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                        </div>
                    </div>
                {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}